### PR TITLE
[Beg] Challenge04_Added Contributor

### PR DESCRIPTION
**Pull request by annimukherjee**
# Challenge 04

Created a `PR`.

- Created a folder under `/contributors` called `annimukherjee`
- Created a markdown file within the above folder so that resultant path is: `contributors/annimukherjee/annimukherjee.md`
- Added 
```
---
name: Aniruddha Mukherjee
github_user_name: annimukherjee
---
```

### CODE REVIEW

**Comment by annimukherjee** [comment]
Completed all the Beginner Challenges.
**Thank you.**

**Comment by annimukherjee** [comment]
# Intermediate 01

[b3c1624](https://github.com/NebulaTris/oss101/pull/31/commits/b3c16247b8312e1d1d16d728d3b13df7b459d16a)
is the `squashed` commit.

**Comment by annimukherjee** [comment]
GPG key added both locally in Git and associated with the GitHub Account.
Commit [fbb5035](https://github.com/NebulaTris/oss101/pull/31/commits/fbb5035f70b6c6b7c7eed3f32bab4134c37715ea) is Verified.

**Comment by NebulaTris** [comment]
Add gist-solutions to your own contributor folder

**Comment by annimukherjee** [comment]
grab- Beg  Challenge04_Added Contributor #31-Arc-003054@2x


Done @NebulaTris

**Comment by annimukherjee** [comment]
@NebulaTris 
Is there an issue?

**Comment by NebulaTris** [comment]
> @NebulaTris 
> Is there an issue?

Earlier there was a conflict due to gist solutions md
Now since it's resolved
I have merged it

**Comment by annimukherjee** [comment]
Thanks so much!
It was great!

**Pull request merged**
